import type { AiService } from "@/types/service";

export const aiServices: AiService[] = [
  {
    id: "ai-chat-subscription",
    title: "AI Chat Subscription",
    slug: "ai-chat-subscription",
    description: "Managed ChatGPT-style access with usage limits, billing, and support.",
    startingPriceNpr: 999,
    category: "chat",
    includedTools: ["GPT-4o", "Claude", "Conversation history"],
    isFeatured: true,
    cta: "View plans",
  },
  {
    id: "assignment-research",
    title: "Assignment and Research Help",
    slug: "assignment-research",
    description: "Structured research, outlines, summaries, and study support.",
    startingPriceNpr: 499,
    category: "content",
    includedTools: ["Research assistant", "Summarizer", "Citation helper"],
    isFeatured: true,
    cta: "Request service",
  },
  {
    id: "coding-assistant",
    title: "Coding Assistant",
    slug: "coding-assistant",
    description: "Debugging, code review, scripts, and developer workflow support.",
    startingPriceNpr: 799,
    category: "coding",
    includedTools: ["Code helper", "Bug explainer", "API assistant"],
    isFeatured: true,
    cta: "Start coding",
  },
  {
    id: "business-automation",
    title: "Business Automation",
    slug: "business-automation",
    description: "Automate repeated business tasks with AI workflows and integrations.",
    startingPriceNpr: 4999,
    category: "automation",
    includedTools: ["Workflow design", "Chatbot setup", "Admin handoff"],
    isFeatured: false,
    cta: "Discuss project",
  },
  {
    id: "developer-api",
    title: "Developer API Access",
    slug: "developer-api",
    description: "Server-side AI API access with NPR billing and monthly usage tracking.",
    startingPriceNpr: 1499,
    category: "api",
    includedTools: ["API keys", "Usage dashboard", "Rate limits"],
    isFeatured: false,
    cta: "Get API access",
  },
  {
    id: "custom-chatbot",
    title: "Custom Chatbot Setup",
    slug: "custom-chatbot",
    description: "A branded chatbot for websites, support, lead capture, or internal teams.",
    startingPriceNpr: 9999,
    category: "custom",
    includedTools: ["Knowledge base", "Widget setup", "Deployment support"],
    isFeatured: false,
    cta: "Book setup",
  },
];

export const featuredAiServices = aiServices.filter((service) => service.isFeatured);
